import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Asim | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bq-white px-10'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>Asim Kachhap</h1>
            <ul className='flex items-center'>
              <li></li>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl'/></li>
              <li></li>
              <li className='bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-2' href="#">Resume</li>
            </ul>
          </nav>
        </section>
      </main>

    </div>
  )
}
